-- liquibase formatted sql

-- changeset yterinc:1

CREATE TABLE IF NOT EXISTS Tasks
(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chatid BIGINT,
    description  VARCHAR(250) NOT NULL,
    title VARCHAR(75) NOT NULL,
    status BOOLEAN
    );